### ISSUE TITLE
Fix travis tests

### ISSUE THREAD

**Issue by rafatower** [CartoDB/odbc_fdw#105]
Travis CI tests are broken. There are at least a couple of things:
- dependencies are pinned to specific versions that no longer exist in existing repos

https://travis-ci.org/CartoDB/odbc_fdw/jobs/598438701
```
E: Package 'mysql-server-core-5.6' has no installation candidate
E: Package 'mysql-client-5.6' has no installation candidate
E: Package 'mysql-server-5.6' has no installation candidate
E: Version '1:09.02.0100-2ubuntu1' for 'odbc-postgresql' was not found
```

- the builds get stuck because of some process waiting for input password on the console:
https://travis-ci.org/CartoDB/odbc_fdw/jobs/598027471
```
namenode: Unknown command
Incorrect configuration: namenode address dfs.namenode.servicerpc-address or dfs.namenode.rpc-address is not configured.
Starting namenodes on []
travis@localhost's password: 

Done: Job Cancelled
```

(looks like hive service)

I did some work fixing dependencies and tried to fix hive as well but couldn't. You can find the PR here: https://github.com/CartoDB/odbc_fdw/pull/102

Please take a look and get the builds :green_apple: again. Aftter fixing the problems pointed out you might need some help from @jgoizueta because CI requires some test services and some encrypted secrets.

**Comment by manmorjim** [comment]
Builds back :green_apple: again!

Travis upgraded its distro from Trusthy to Xenial so this requires some changes in configuration:
- [It has preinstalled a MySQL 5.7](https://docs.travis-ci.com/user/reference/xenial/#databases-and-services) so we had to update mysql dependencies from 5.6 to 5.7
- Using RSA keys to authorize ssh connections.

Also there was a misconfiguration in the file `odbcinst.ini` with the MySQL driver.

**Comment by manmorjim** [comment]
MSSQLServer tests have been temporarily disabled because they were being executed in a remote machine which is unavailable at this moment. I opened #108 in order to enable them again.
