### ISSUE TITLE
Cannot create extension: undefined symbol: ExecStoreTuple

### ISSUE THREAD

**Issue by thomas-maschler** [CartoDB/odbc_fdw#109]
### Context
I am trying to install odbc_fdw in a local deployment.
I use Fedora 30 with PostgreSQL 12 and PostGIS 2.5

I manage to build odbc_fdw 0.4.0. But when I try to install the extension in PostGIS I get an error
`ERROR: could not load library "/usr/pgsql-12/lib/odbc_fdw.so": /usr/pgsql-12/lib/odbc_fdw.so: undefined symbol: ExecStoreTuple`

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

```
sudo dnf install -y postgresql12-odbc mysql-connector-odbc unixODBC-devel
curl -SL https://github.com/CartoDB/odbc_fdw/archive/0.4.0.tar.gz | tar -xzC /usr/src
cd /usr/src/odbc_fdw-0.4.0 && make  && sudo make install
su postgres
psql -d template_postgis -c "CREATE EXTENSION odbc_fdw"
```

### Current Result
I cannot create the extension:

`ERROR: could not load library "/usr/pgsql-12/lib/odbc_fdw.so": /usr/pgsql-12/lib/odbc_fdw.so: undefined symbol: ExecStoreTuple`

odbc_fdw.so is present but seems to be corrupted?

### Expected result
I can install the extension

### System trying to connect to and version
Trying to install on
- Fedora 30 
- PostgreSQL 12 
- PostGIS 2.5

**Comment by Algunenano** [comment]
Duplicates https://github.com/CartoDB/odbc_fdw/issues/103

**Comment by thomas-maschler** [comment]
Thanks, with #104 this works now for me, too
