### ISSUE TITLE
ERROR: Executing ODBC query

### ISSUE THREAD

**Issue by sugerdudu** [CartoDB/odbc_fdw#28]
Hello, My situation is as follows:

**One:**
Use "isql -v test2" is successed.

**Two:**
But error  in postgresql.
Use
 OPTIONS (driver 'MSSQLServer');

ERROR: Executing ODBC query.

**Three:**
Use
 OPTIONS (dsn 'test');
Dns "test" config is MS SqlServer 2012

Error too
Always show "Connecting to driver"

How can I solve. 
Thinks

**Comment by sugerdudu** [comment]
No problem. 

Solved.

Thinks

**Comment by rafatower** [comment]
It would be really nice I you could share your findings with the us :smile:
