### ISSUE TITLE
odbc_fdw support for postgres 9.6

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/odbc_fdw#42]
Was just wondering if you have tested this with Postgresql 9.6 as I cannot get it to work.

A sample of the errors are below:

```
odbc_fdw.c:1265:59: error: incompatible type for argument 3 of ‘create_foreignscan_path’

           (Path *) create_foreignscan_path(root, baserel, baserel->rows, startup_cost, total_cost,

                                                           ^

In file included from odbc_fdw.c:51:0:

/usr/include/postgresql/9.6/server/optimizer/pathnode.h:90:21: note: expected ‘PathTarget * {aka struct PathTarget *}’ but argument is of type ‘double’

 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,

                     ^

In file included from /usr/include/postgresql/9.6/server/access/tupdesc.h:19:0,

                 from /usr/include/postgresql/9.6/server/funcapi.h:20,

                 from odbc_fdw.c:26:

/usr/include/postgresql/9.6/server/nodes/pg_list.h:69:18: error: incompatible type for argument 6 of ‘create_foreignscan_path’

 #define NIL      ((List *) NULL)

                  ^

odbc_fdw.c:1266:11: note: in expansion of macro ‘NIL’

           NIL, NULL, NULL, NIL /* no fdw_private list */));

           ^

In file included from odbc_fdw.c:51:0:

/usr/include/postgresql/9.6/server/optimizer/pathnode.h:90:21: note: expected ‘Cost {aka double}’ but argument is of type ‘List * {aka struct List *}’

 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,

                     ^

In file included from /usr/include/postgresql/9.6/server/access/tupdesc.h:19:0,

                 from /usr/include/postgresql/9.6/server/funcapi.h:20,

                 from odbc_fdw.c:26:

/usr/include/postgresql/9.6/server/nodes/pg_list.h:69:18: warning: passing argument 9 of ‘create_foreignscan_path’ from incompatible pointer type [-Wincompatible-pointer-types]

 #define NIL      ((List *) NULL)

                  ^

odbc_fdw.c:1266:28: note: in expansion of macro ‘NIL’

           NIL, NULL, NULL, NIL /* no fdw_private list */));

                            ^

In file included from odbc_fdw.c:51:0:

/usr/include/postgresql/9.6/server/optimizer/pathnode.h:90:21: note: expected ‘Path * {aka struct Path *}’ but argument is of type ‘List * {aka struct List *}’

 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,

                     ^

odbc_fdw.c:1265:20: error: too few arguments to function ‘create_foreignscan_path’

           (Path *) create_foreignscan_path(root, baserel, baserel->rows, startup_cost, total_cost,

                    ^

In file included from odbc_fdw.c:51:0:

/usr/include/postgresql/9.6/server/optimizer/pathnode.h:90:21: note: declared here

 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,

                     ^

odbc_fdw.c: In function ‘odbcIterateForeignScan’:

odbc_fdw.c:1636:11: warning: variable ‘buf_used’ set but not used [-Wunused-but-set-variable]

    size_t buf_used;

           ^

<builtin>: recipe for target 'odbc_fdw.o' failed

make: *** [odbc_fdw.o] Error 1
```

**Comment by jgoizueta** [comment]
It seems that there has been some changes in the FDW API, but I can't find them summarised anywhere, we'll have to figure out from the 9.6 docs and the source code...

**Comment by ethervoid** [comment]
Yes, I agree. That's what I thought.

**Comment by snhirsch** [comment]
This is sort of a show stopper for our 9.6 upgrade.  Are you folks getting the answers you need from the pgSQL developer community?

**Comment by snhirsch** [comment]
I can compile the code with this minor change.  Based on the postgresql_fdw code, I believe it's acceptable to pass NULL for that new parm.  This hasn't been tested yet (the installcheck appears to make incorrect assumptions about my environment and has never worked here).

`diff --git a/odbc_fdw.c b/odbc_fdw.c
index 8471833..c15600a 100644
--- a/odbc_fdw.c
+++ b/odbc_fdw.c
@@ -1042,7 +1042,7 @@ static void odbcGetForeignPaths(PlannerInfo *root, RelOptInfo *baserel, Oid fore
odbcEstimateCosts(root, baserel, &startup_cost, &total_cost, foreigntableid);

add_path(baserel,
- (Path *) create_foreignscan_path(root, baserel, baserel->rows, startup_cost, total_cost,
+ (Path *) create_foreignscan_path(root, baserel, NULL, baserel->rows, startup_cost, total_cost,
NIL, NULL, NULL, NIL /* no fdw_private list */));

#ifdef DEBUG
`

**Comment by robe2** [comment]
I submitted a pull request https://github.com/CartoDB/odbc_fdw/pull/46  to fix this for 9.6 without impacting 9.5.  I tested on both under windows and seems to work now on both 9.5 and 9.6.

**Comment by rafatower** [comment]
Sorry about the delay. On our side we have to check a a few things:
- license
- CLA
- regression tests

**Comment by ethervoid** [comment]
Hi @robe2 sorry for the delay, to accept the pull request we need you first to send us a signed CLA, more details [here](https://github.com/CartoDB/odbc_fdw/blob/master/CONTRIBUTING.md). Would you mind doing this, please?

**Comment by snhirsch** [comment]
Glad to see this moving forward.  Was beginning to wonder if this project was still actively maintained.

**Comment by ethervoid** [comment]
This issue has two phases:

- First, configure Travis build to support compilation and tests execution against PostgreSQL 9.5 and 9.6 done in #55 
- Second is have the CLA signed by @robe2 to integrate #46

**Comment by robe2** [comment]
@ethervoid Sorry didn't see your question until now. When I got an email today.  Sounds like @javitonino  came up with similar patch. If you still need me to sign the CLA, I'd be happy to.

**Comment by agnesgyorfi** [comment]
Hi @robe2,

Thanks so much for creating the pull request!  Would you please review the attached CLA, sign (if you made this contribution while working for an employer or client, we'd probably need them to "sign as an Entity"), and let me know if you have questions?

Once you have (or the Entity has signed, please go ahead and return it to me via email at cla-support@carto.com. 

Thanks so much!

[CartoDB, Inc. - Contributor License Agreement v1.3 20150922.pdf](https://github.com/CartoDB/odbc_fdw/files/773505/CartoDB.Inc.-.Contributor.License.Agreement.v1.3.20150922.pdf)

**Comment by agnesgyorfi** [comment]
Hi @robe2 

Just checking in to make sure you were able to open that CLA file.  Please let me know if you have any questions!

Thank you!

**Comment by pramsey** [comment]
Should be covered by #69

**Comment by pramsey** [comment]
Done and merged and happy.
