### ISSUE TITLE
Queries is not pushed down to foreign database

### ISSUE THREAD

**Issue by vugark** [CartoDB/odbc_fdw#44]
I created simple foreign table like this which gets data from foreign Impala database:

CREATE FOREIGN table odbc_table (
    customer_id BIGINT
)
SERVER odbc_impala_server OPTIONS (
    schema 'dwh',
    table 'tracking_fact_session_event'
);

When I execute this simple query below odbc_fdw doesn't push that WHERE clause to Impala database. But extracts all remote data and applies filter on PostgreSQL database side which isn't effective.

select customer_id from odbc_table where customer_id = 125801071 

This query takes a few seconds on Impala side but a few minutes when selecting from foreign table. Also using this EXPLAIN VERBOSE statement I am sure that query isn't pushed down:

EXPLAIN VERBOSE select customer_id from odbc_table where customer_id = 125801071;

The same problem occur with other SQL queries as well. For example,

select count(customer_id) from odbc_table

isn't pushed down also.

**Comment by robe2** [comment]
The count() aggregate would not be pushed down.  That is an issue with the underlying PostgreSQL FDW api which doesn't support aggregate pushdown until PostgreSQL 10.  Aggregate push down support has been recently committed to PostgreSQL 10.  

https://www.depesz.com/2016/10/25/waiting-for-postgresql-10-postgres_fdw-push-down-aggregates-to-remote-servers/
