### ISSUE TITLE
Restyle the code

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/odbc_fdw#5]
- [x] Convert leading spaces to tabs (4-space stops) as required by PostgreSQL code conventions
- [x] Adopt coding style and apply to the code (BSD indent {} style, CamelCase for types and exported functions, snake_case for internal functions and variables.
- [x] Remove debug messages (or at list use `RAISE DEBUG` instead of `NOTICE`)

**Comment by jgoizueta** [comment]
@rafatower:  What [style](https://en.wikipedia.org/wiki/Indent_style#Styles) do you prefer? I'd rather use something similar to K&R and 2-space indents.

There's also a ton of C coding style guides. If you have a preferred one to apply here we can use it. Otherwise let's just settle the indent style and apply common sense.

**Comment by rafatower** [comment]
Send your proposals. I'd prefer picking up one existing code style guide rather than reinventing the wheel.

https://www.postgresql.org/docs/current/static/source-format.html

postgres uses tabs for indentation :/

**Comment by jgoizueta** [comment]
Now it seems obvious to be we should follow existing PG conventions (despite the tab/4 space indent, grrr)
