### ISSUE TITLE
MS SQL column of type nvarchar(max) fails to import (maps to varchar(0))

### ISSUE THREAD

**Issue by zam6ak** [CartoDB/odbc_fdw#59]
### Context
*Please explain here below what you were doing when the issue happened*

```
CREATE SCHEMA fdw;
IMPORT FOREIGN SCHEMA dbo
LIMIT TO (test1, test2)
FROM SERVER sql_server
INTO fdw
OPTIONS (
    odbc_DATABASE 'mssql_test'
)

```

### Current Result
foreign tables fail to import

```
NOTICE:  Data type not supported (-2) for column description
ERROR:  length for type varchar must be at least 1
LINE 1: ..._by" integer, "user_id" integer, "description" varchar(0)...
```

### System trying to connect to and version
MS SQL Server 2012

### Additional info
It seems that `nvarchar(max)` on MSQ SQL server is being mapped to `varchar(0) ` which is invalid data type....Perhaps it should just map to `text` ,,,,,

**Comment by rafatower** [comment]
cc/ @jgoizueta just FYI
