### ISSUE TITLE
Create a binary package

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/odbc_fdw#6]
We should create binary packages for Ubuntu and Red Hat.

Tasks for installing in production servers and into users' databases will also be needed.

Dev. dependencies for compiling (Ubuntu):

```bash
apt-get install -y unixodbc-dev
apt-get install -y postgresql-server-dev-9.5
```

Compilation process: 

```bash
git clone https://github.com/CartoDB/odbc_fdw.git
cd odbc_fdw
PATH=$(pg_config --bindir):$PATH make USE_PGXS=1
sudo PATH=$(pg_config --bindir):$PATH make USE_PGXS=1 install
```
(The `USE_PGXS` will eventually be removed)

Run time dependencies:

```bash
apt-get install -y odbcinst unixodbc
```

ODBC drivers:

Supported ODBC drivers will have to be installed in production servers too. (should we add them as dependencies of these package?)

Example installation:

```bash
# MySQL driver
sudo apt-get install libmyodbc
sudo odbcinst -i -d -f /usr/share/libmyodbc/odbcinst.ini

# PostgreSQL driver
sudo apt-get install odbc-postgresql

# SQLite driver
sudo apt-get install libsqliteodbc
```

Once the binary package has been deployed, the extension can be created/updated into user databases.

**Comment by rafatower** [comment]
> (The USE_PGXS will eventually be removed)

I doubt it. Actually I think that's mandatory/

> odbcinst

is that really a runtime dependency? well, we'll figure it...

**Comment by jgoizueta** [comment]
I problably added `odbcinst` because of the example I wrote, which needed it. We don't (we write `/etc/odbcinst.ini` directly)

**Comment by jgoizueta** [comment]
The removal of `USE_PGXS` was because of this: http://blog.pgxn.org/post/20908326485/lose-use-pgxs

**Comment by rafatower** [comment]
this is already done
