### ISSUE TITLE
Update version and create release notes

### ISSUE THREAD

**Issue by skgsergio** [CartoDB/odbc_fdw#73]
As part of our current work we would need to have the version updated and the release notes ready in order to be able to package this.

We have no preferences on versioning/tagging, we can continue using x.y.z if you want.

**Comment by rafatower** [comment]
Sorry it took me a bit longer than I expected.

I created the release notes here: https://github.com/CartoDB/odbc_fdw/blob/master/NEWS.md

I also created a release procedure here: https://github.com/CartoDB/odbc_fdw/blob/master/NEWS.md

After reviewing everything, I tagged and released the latest changes in a version 0.3.0: https://github.com/CartoDB/odbc_fdw/releases/tag/0.3.0

Everything is OK to my best knowledge. Given the amount of possible combinations (PostgreSQL and foreign server types), we have to rely heavily in CI. Everything looks fine in travis test matrix: https://travis-ci.org/CartoDB/odbc_fdw/builds/343870091

**Comment by skgsergio** [comment]
Thanks, I'll create the package now.
