### ISSUE TITLE
ODBC FDW with DB2 forces us to create upper case table name

### ISSUE THREAD

**Issue by sravikrishna3** [CartoDB/odbc_fdw#90]
I found a bug in ODBC FDW for PG.  I am using it to connect to DB2 10.5 on Linux. 
 It seems when i write a query like

select col_a from table_a (where table_a is foreign data table)

it converts it to select "col_a" from "table_a".  Note the double quotes around the col name.  The problem with this is that DB2 makes the col name case sensitive if wrapped around double quotes.  Since all col names were created without quotes, they were stored in upper case and that works fine case insensitive. In this case select "col_a" returns error col not found.
Workaround:  Create the foreign data table in PG with upper case cols wrapped in quote.

**Comment by gferrette** [comment]
Hello sravikrishna3!

I'm trying to connect to DB2 tables via odbc_fdw and i'm getting the error "ERROR:  Executing ODBC query".
The connection through isql is working perfectly, but when i try to execute queries through odbc_fdw i'm getting this error. 

Please, can you help me?

Follow below my script:

CREATE SERVER odbc_server
  FOREIGN DATA WRAPPER odbc_fdw
  OPTIONS (dsn 'BUNI01');

CREATE FOREIGN TABLE
  teste_fed_odbc (
    "ID_PAREC_SOL" integer,
    "ID_SOL" integer,
    "ID_USUAR_FAEPEX" integer,
    "ID_COMI_EXEC" integer,
    "ID_COMI_EDI" integer
  )
  SERVER odbc_server
  OPTIONS (
    odbc_DATABASE 'BUNI01',
    schema 'FAEP',
    sql_query 'select ID_PAREC_SOL, ID_SOL, ID_USUAR_FAEPEX, ID_COMI_EXEC, ID_COMI_EDI from faep.rfpx13'
  );

**Comment by sravikrishna3** [comment]
Hello I am not the author of FDW. You need to ask the author. My personal view is that odbc_fdw is buggy and not working with db2
